export const USER_APPS_REQUEST = 'USER_APPS_REQUEST';
export const USER_APPS_SUCCESS = 'USER_APPS_SUCCESS';
export const USER_APPS_FAIL = 'USER_APPS_FAIL';
export const USER_APPS_RESET = 'USER_APPS_RESET';

export const POST_APP_REQUEST = 'POST_APP_REQUEST';
export const POST_APP_SUCCESS = 'POST_APP_SUCCESS';
export const POST_APP_FAIL = 'POST_APP_FAIL';
