let colors = {
  white: 'white',
  red: 'red',
  salmon: 'salmon',
  orange: 'orange',
  gold: 'gold',
  yellow: 'yellow',
  lightGreen: 'light-green',
  green: 'green',
  darkGreen: 'dark-green',
  blueGreen: 'blue-green',
  lightBlue: 'light-blue',
  blue: 'blue',
  navy: 'navy',
  purple: 'purple',
  black: 'black',
  gray: 'gray',
  offPurple: 'off-purple',
};

export let colorsArr = [
  'white',
  'red',
  'salmon',
  'orange',
  'gold',
  'yellow',
  'light-green',
  'green',
  'dark-green',
  'blue-green',
  'light-blue',
  'blue',
  'navy',
  'purple',
  'black',
  'gray',
  'off-purple',
];
export default colors;
