let colors = {
  white: 'white',
  red: 'red',
  salmon: 'salmon',
  orange: 'orange',
  gold: 'gold',
  yellow: 'yellow',
  lightGreen: 'light-green',
  green: 'green',
  darkGreen: 'dark-green',
  blueGreen: 'blue-green',
  lightBlue: 'light-blue',
  blue: 'blue',
  navy: 'navy',
  purple: 'purple',
  black: 'black',
  gray: 'gray',
  offPurple: 'off-purple',
};

export let colorsArr = [
  'red',
  'salmon',
  'light-red',
  'light-pink',
  'bubblegum',
  'hot-pink',
  'orange',
  'gold',
  'light-orange',
  'yellow',
  'light-yellow',
  'off-white',
  'dark-green',
  'green',
  'light-green',
  'light-blue',
  'blue',
  'true-blue',
  'cyan',
  'baby-blue',
  'light-cyan',
  'light-purple',
  'purple',
  'royal-purple',
  'white',
  'ashe',
  'silver',
  'gray',
  'navy',
  'black',
  'default',
];
export default colors;
